// The <ggsql-hep> custom element: renders a .hep plot document with the
// hephaestus-svg-wasm browser client. The ES module is bundled statically
// into ggsql_hep.js; the wasm binary and Roboto faces arrive through
// `globalThis.ggsqlHepAssets`, set by hephaestus-assets.js, which travels
// with the widget's htmlDependency. Because nothing is resolved by URL at
// runtime, the widget works identically in served and self-contained
// documents — htmltools includes the dependency exactly once per document
// either way. The wasm module is initialised lazily and shared by every
// widget on the page.

import initHep, {
  registerFont,
  setGenericFamily,
  PlotView,
} from "hephaestus-svg-wasm";

const ROBOTO_FACES = ["regular", "bold", "italic", "bolditalic"] as const;

// CSS weight/style per face, for the @font-face blocks that let the browser
// draw the family wasm shaped with.
const ROBOTO_FACE_CSS: Record<(typeof ROBOTO_FACES)[number], [number, string]> =
  {
    regular: [400, "normal"],
    bold: [700, "normal"],
    italic: [400, "italic"],
    bolditalic: [700, "italic"],
  };

const FACE_STYLE_ID = "ggsql-hep-roboto-faces";

export type WidgetValue = {
  // Base64-encoded .hep document
  hep: string;
};

type HepAssets = {
  version: string;
  // gzip-compressed, base64-encoded hephaestus_svg_wasm_bg.wasm
  wasm: string;
  // Same encoding, per Roboto face (TTF)
  fonts: Record<string, string>;
};

declare global {
  // Set by hephaestus-assets.js (AUTO-GENERATED by tools/build-hep-assets.mjs)
  var ggsqlHepAssets: HepAssets | undefined;
}

function decodeBase64(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

async function gunzip(bytes: Uint8Array): Promise<Uint8Array> {
  const stream = new Blob([bytes as BlobPart])
    .stream()
    .pipeThrough(new DecompressionStream("gzip"));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

type PlotViewInstance = InstanceType<typeof PlotView>;

let modulePromise: Promise<unknown> | null = null;

function loadHep(): Promise<unknown> {
  if (!modulePromise) {
    modulePromise = (async () => {
      const assets = globalThis.ggsqlHepAssets;
      if (!assets) {
        throw new Error(
          "ggsql: hephaestus-svg assets are missing " +
            "(globalThis.ggsqlHepAssets is unset). The hephaestus-assets.js " +
            "dependency must load before the ggsql widget script."
        );
      }
      await initHep({
        module_or_path: await gunzip(decodeBase64(assets.wasm)),
      });
      // Fonts must be registered twice over: with the shaper, which
      // measures, and with the page as @font-face, which draws. Without the
      // shaper half the layout collapses (a browser enumerates no system
      // fonts); without the page half the browser substitutes another family
      // for the runs wasm measured as Roboto.
      const faceCss: string[] = [];
      for (const face of ROBOTO_FACES) {
        const bytes = await gunzip(decodeBase64(assets.fonts[face]));
        registerFont(bytes);
        const [weight, style] = ROBOTO_FACE_CSS[face];
        const url = URL.createObjectURL(
          new Blob([bytes as BlobPart], { type: "font/ttf" })
        );
        faceCss.push(
          `@font-face{font-family:'Roboto';font-style:${style};` +
            `font-weight:${weight};font-display:block;` +
            `src:url('${url}') format('truetype');}`
        );
      }
      if (!document.getElementById(FACE_STYLE_ID)) {
        const style = document.createElement("style");
        style.id = FACE_STYLE_ID;
        style.textContent = faceCss.join("\n");
        document.head.appendChild(style);
      }
      setGenericFamily("sans-serif", ["Roboto"]);
    })();
  }
  return modulePromise;
}

export class HepWidget extends HTMLElement {
  private view: PlotViewInstance | null = null;
  private pending: Promise<void> | null = null;

  renderValue(x: WidgetValue): void {
    const bytes = decodeBase64(x.hep);
    this.pending = (async () => {
      await loadHep();
      // A stale render resolved after a newer one must not win — renderValue
      // is async because the module load is.
      if (!this.isConnected && this.view) return;
      this.view?.free();
      // defaultFont is false: fonts were registered explicitly in loadHep()
      // from the embedded assets, not fetched from a URL. Sizing is left to
      // PlotView's own container observer (autoResize by default).
      this.view = await PlotView.create(this, bytes, {
        defaultFont: false,
      });
      for (const warning of this.view.warnings) {
        console.warn("ggsql:", warning);
      }
    })().catch((err) => {
      this.textContent = `ggsql widget failed: ${err?.message ?? err}`;
      throw err;
    });
  }

  resize(): void {
    // PlotView observes the container itself; a direct resize just nudges it.
    this.view?.redraw();
  }

  finalize(): void {
    this.view?.free();
    this.view = null;
  }

  disconnectedCallback(): void {
    this.finalize();
  }
}
