#!/usr/bin/env bash
#
# Updates the hephaestus-svg-wasm browser client: installs the pinned version
# from npm, regenerates inst/htmlwidgets/lib/hephaestus-svg/hephaestus-assets.js
# (the wasm binary and Roboto faces, gzip + base64 encoded onto a global), and
# records the version in R/hep-version.R.
# Source: https://registry.npmjs.org/hephaestus-svg-wasm
#
set -euo pipefail

HEPHAESTUS_VERSION="0.4.1"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$SCRIPT_DIR/.."

echo "Installing hephaestus-svg-wasm@$HEPHAESTUS_VERSION ..."
npm install --save-dev --save-exact "hephaestus-svg-wasm@$HEPHAESTUS_VERSION" \
  --prefix "$REPO_ROOT"

node "$SCRIPT_DIR/build-hep-assets.mjs"

VERSIONS_FILE="$REPO_ROOT/R/hep-version.R"
cat > "$VERSIONS_FILE" <<EOF
# AUTO-GENERATED by tools/update-hephaestus.sh — do not edit by hand.
# To update, change HEPHAESTUS_VERSION in tools/update-hephaestus.sh and rerun it.

hep_version <- "$HEPHAESTUS_VERSION"
EOF

echo "Rebuilding the widget bundle (npm run build) ..."
npm run build --prefix "$REPO_ROOT"

echo "Done. Updated R/hep-version.R, hephaestus-assets.js, and ggsql_hep.js."
