#!/usr/bin/env bash
#
# Downloads the vendored hephaestus-svg-wasm browser client into
# inst/htmlwidgets/lib/hephaestus-svg/.
# Source: https://registry.npmjs.org/hephaestus-svg-wasm
#
set -euo pipefail

HEPHAESTUS_VERSION="0.4.1"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../inst/htmlwidgets/lib/hephaestus-svg"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Downloading hephaestus-svg-wasm@$HEPHAESTUS_VERSION ..."
curl -fsSL "https://registry.npmjs.org/hephaestus-svg-wasm/-/hephaestus-svg-wasm-$HEPHAESTUS_VERSION.tgz" \
  -o "$TMP_DIR/hephaestus.tgz"
tar xzf "$TMP_DIR/hephaestus.tgz" -C "$TMP_DIR"

mkdir -p "$LIB_DIR/fonts"
for f in \
  hephaestus-svg.js \
  hephaestus-svg.d.ts \
  hephaestus_svg_wasm.js \
  hephaestus_svg_wasm.d.ts \
  hephaestus_svg_wasm_bg.wasm; do
  cp "$TMP_DIR/package/$f" "$LIB_DIR/$f"
done
cp "$TMP_DIR/package/fonts/"* "$LIB_DIR/fonts/"

VERSIONS_FILE="$SCRIPT_DIR/../R/hep-version.R"
cat > "$VERSIONS_FILE" <<EOF
# AUTO-GENERATED by tools/update-hephaestus.sh — do not edit by hand.
# To update, change HEPHAESTUS_VERSION in tools/update-hephaestus.sh and rerun it.

hep_version <- "$HEPHAESTUS_VERSION"
EOF

echo "Done. Updated R/hep-version.R and vendored hephaestus-svg-wasm."
